apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuweb-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      # 해당 Lables을 3개 생성함
      app: kuweb-label
  template:
    # 개수가 부족하면 template을 보고 pod 생성
    metadata:
      name: kuweb-pod
      labels:
        app: kuweb-label
    spec:
      containers:
        - name: kuweb
          image: testweb:1.0
          resources:
            requests:
              memory: '128Mi'
              cpu: '500m'
            limits:
              memory: '256Mi'
              cpu: '1000m'
          ports:
            - containerPort: 8080
              protocol: TCP
