apiVersion: v1
kind: Pod
metadata:
  name: kuweb-pod
spec:
  containers:
  - name: kuweb
    image: testweb:1.0
    resources:
      # 최소 자원 요구량
      requests:
        memory: "128Mi"
        cpu: "500m"
      # 최대 자원 요구량
      limits:
        memory: "256Mi"
        cpu: "1000m"
    ports:
      - containerPort: 8080
        protocol: TCP
