apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    name: emptydir-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - cat
    tty: true
    # 아래에 설정한 볼륨을 컨테이너 설정에서 사용한다.
    volumeMounts:
    - mountPath: /root/tmp
      name: emptydir-volume
  - name: alpine
    image: alpine:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - cat
    tty: true
    # 아래에 설정한 볼륨을 컨테이너 설정에서 사용한다.
    volumeMounts:
    - mountPath: /root/tmp
      name: emptydir-volume
  # 사용하려는 볼륨을 먼저 선언한다.
  volumes:
  - name: emptydir-volume
    emptyDir: {}
