apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    name: hostpath-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /root/tmp
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /private/tmp
